require 'rake/clean'

CC = 'gcc'
SRCS = FileList['**/*.c']
OBJS = SRCS.ext('o')

CLEAN.include(OBJS)
CLOBBER.include('hello')

task default: 'hello'

desc 'Compile C program'
file 'hello' => OBJS do |t|
  sh "#{CC} -o #{t.name} #{t.prerequisites.join(' ')}"
end

rule '.o' => '.c' do |t|
  sh "#{CC} -c #{t.source}"
end
